# Generated by Django 5.2.6 on 2025-09-13 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="reminder_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="habit",
            name="send_reminder",
            field=models.BooleanField(default=False),
        ),
    ]
